<?php

// define("API_URL", "https://{{ip}}:8443/");

define("EMPLOYMENT_STATUS_TERMINATE", 1);
define("EMPLOYMENT_STATUS_FT_CONTRACT", 2);
define("EMPLOYMENT_STATUS_FT_INTERNSHIP", 3);
define("EMPLOYMENT_STATUS_FT_PERMANENT", 4);
define("EMPLOYMENT_STATUS_PT_CONTRACT", 5);
define("EMPLOYMENT_STATUS_PT_INTERNSHIP", 6);
define("EMPLOYMENT_STATUS_PT_PERMANENT", 7);

define("DATA_STATUS_EXIST", 1);
define("DATA_STATUS_DELETED", 0);